# Horários ônibus, linha 150, Terminal Fazenda/Cordeiros

http://200.195.174.242:86/ITSReports/

ITS Reports - Operação - Cumprimento de Serviço

Data: 2018 / 2021

legenda | descrição
--------|------------------
IP      | Inicio Previsto
IR      | Inicio Realizado
FP      | Fim Previsto
FR      | Fim Realizado
PP      | Prefixo Previsto
PR      | Prefixo Realizado
V       | Viagem

# Leitura dos dados

In [1]:
import numpy as np
import pandas as pd
import os
from datetime import date, timedelta, datetime

pd.set_option('display.max_columns', 45)

In [2]:
wpath = os.getcwd()
path = f'{wpath}/dados/linha_150'
pastas = os.listdir(path)
print(pastas)

['2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12', '2019-01', '2019-02', '2019-03', '2019-04', '2019-05', '2019-06', '2019-07', '2019-08', '2019-09', '2019-10', '2019-11', '2019-12', '2020-01', '2020-02', '2020-03', '2020-04', '2020-05', '2020-06', '2020-07', '2020-08', '2020-09', '2020-10', '2020-11', '2020-12', '2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06', '2021-07', '2021-08', '2021-09']

In [3]:
dadosXls = []

for p in pastas:
    arquivos = os.listdir(f'{path}/{p}')
    for x in arquivos:
        if '.xlsx' in x:
            data = pd.read_excel(f'{path}/{p}/{x}')
            dadosXls.append(data)

dadosXls = pd.concat(dadosXls)
dadosXls.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cumprimento de Serviço,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Data: 10/01/2018 - Linha: 150 - Todos os Servi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
dadosXls['Unnamed: 3'] = dadosXls['Unnamed: 3'].fillna(method="ffill")

dadosXls['Unnamed: 1'].where(
    dadosXls['Unnamed: 1'].str.contains("Data: "), inplace=True)

dadosXls['Unnamed: 1'] = dadosXls['Unnamed: 1'].fillna(method="ffill")

In [5]:
dados = dadosXls.loc[dadosXls['Unnamed: 5'].isin(['IDA', 'VOLTA'])]

In [6]:
dados.head(3)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
11,NaN,Data: 10/01/2018 - Linha: 150 - Todos os Servi...,NaN,Serviço: 11,1,IDA,10/01 05:25,10/01 05:25,NaN,NaN,10/01 05:55,10/01 05:39,-,-,Terminal Cordeiros,Terminal Fazenda,11,150_A - Terminal Cordeiros > Terminal Fazenda,--,--,"0,00 %",NaN,Manual,Paradas,HistÃ³rico
12,NaN,Data: 10/01/2018 - Linha: 150 - Todos os Servi...,NaN,Serviço: 11,2,VOLTA,10/01 05:55,10/01 05:58,NaN,NaN,10/01 06:25,10/01 06:12,-,-,Terminal Fazenda,Terminal Cordeiros,11,150_A - Terminal Cordeiros > Terminal Fazenda,--,--,"0,00 %",NaN,Manual,Paradas,HistÃ³rico
13,NaN,Data: 10/01/2018 - Linha: 150 - Todos os Servi...,NaN,Serviço: 11,3,IDA,10/01 06:35,10/01 06:37,NaN,NaN,10/01 07:05,10/01 06:54,-,-,Terminal Cordeiros,Terminal Fazenda,11,150_A - Terminal Cordeiros > Terminal Fazenda,--,--,"0,00 %",NaN,Manual,Paradas,HistÃ³rico

In [7]:
dados['date'] = pd.to_datetime(
    dados['Unnamed: 1'].str.slice(6, 16), format='%d/%m/%Y')

dados['linha'] = dados['Unnamed: 1'].str.slice(26, 29)

/tmp/ipykernel_221/351075479.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['date'] = pd.to_datetime(
/tmp/ipykernel_221/351075479.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['linha'] = dados['Unnamed: 1'].str.slice(26, 29)

In [10]:
dados['iniciortemp'] = dados['Unnamed: 1'].str[12: 16]+'-' + dados['Unnamed: 1'].str[9: 11]+'-' + \
    dados['Unnamed: 1'].str[6: 8]+' ' + dados['Unnamed: 7'].str[6: 8] + \
    ':' + dados['Unnamed: 7'].str[9: 11]

dados['inicioregistr'] = dados['iniciortemp'].astype('datetime64[ns]')

/tmp/ipykernel_221/2820154187.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['iniciortemp'] = dados['Unnamed: 1'].str[12: 16]+'-' + dados['Unnamed: 1'].str[9: 11]+'-' + \

ParserError: Unknown string format: 2018-01-10 :